// Code generated by protoc-gen-go. DO NOT EDIT.
// source: currency_message.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.w
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency struct {
	Left                 string   `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                string   `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	Value                float32  `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5383d524114447c, []int{0}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetLeft() string {
	if m != nil {
		return m.Left
	}
	return ""
}

func (m *Currency) GetRight() string {
	if m != nil {
		return m.Right
	}
	return ""
}

func (m *Currency) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Currency) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*Currency)(nil), "example.Currency")
}

func init() { proto.RegisterFile("currency_message.proto", fileDescriptor_e5383d524114447c) }

var fileDescriptor_e5383d524114447c = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2e, 0x2d, 0x2a,
	0x4a, 0xcd, 0x4b, 0xae, 0x8c, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x95, 0x12, 0x2a, 0xc9, 0x2f,
	0xc8, 0x4c, 0x8e, 0xcf, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0x83, 0x48, 0x2a, 0x95, 0x73, 0x71, 0x38,
	0x43, 0xb5, 0x09, 0x09, 0x71, 0xb1, 0xe4, 0xa4, 0xa6, 0x95, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x45, 0x99, 0xe9, 0x19, 0x25, 0x12, 0x4c, 0x60, 0x41,
	0x08, 0x07, 0x24, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x14, 0x04,
	0xe1, 0x80, 0xf4, 0x97, 0x64, 0xe6, 0xa6, 0x4a, 0xb0, 0x40, 0xf4, 0x83, 0xd8, 0x56, 0xe2, 0x5d,
	0x5b, 0x25, 0xd8, 0xcb, 0x53, 0x13, 0x4b, 0x32, 0x52, 0x8b, 0x26, 0x6d, 0x95, 0xe0, 0x80, 0xb9,
	0xd1, 0x89, 0x2d, 0x8a, 0x25, 0x37, 0x31, 0x33, 0x2f, 0x89, 0x0d, 0xec, 0x0e, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x76, 0xe4, 0x98, 0x86, 0xbe, 0x00, 0x00, 0x00,
}
