// Code generated by protoc-gen-go. DO NOT EDIT.
// source: weather_message.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Weather struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Temperature          float32  `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Wind                 float32  `protobuf:"fixed32,3,opt,name=wind,proto3" json:"wind,omitempty"`
	Visibility           int32    `protobuf:"varint,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Weather              string   `protobuf:"bytes,5,opt,name=weather,proto3" json:"weather,omitempty"`
	Time                 string   `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weather) Reset()         { *m = Weather{} }
func (m *Weather) String() string { return proto.CompactTextString(m) }
func (*Weather) ProtoMessage()    {}
func (*Weather) Descriptor() ([]byte, []int) {
	return fileDescriptor_798b5547218179bb, []int{0}
}

func (m *Weather) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weather.Unmarshal(m, b)
}
func (m *Weather) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weather.Marshal(b, m, deterministic)
}
func (m *Weather) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weather.Merge(m, src)
}
func (m *Weather) XXX_Size() int {
	return xxx_messageInfo_Weather.Size(m)
}
func (m *Weather) XXX_DiscardUnknown() {
	xxx_messageInfo_Weather.DiscardUnknown(m)
}

var xxx_messageInfo_Weather proto.InternalMessageInfo

func (m *Weather) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Weather) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Weather) GetWind() float32 {
	if m != nil {
		return m.Wind
	}
	return 0
}

func (m *Weather) GetVisibility() int32 {
	if m != nil {
		return m.Visibility
	}
	return 0
}

func (m *Weather) GetWeather() string {
	if m != nil {
		return m.Weather
	}
	return ""
}

func (m *Weather) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*Weather)(nil), "example.Weather")
}

func init() { proto.RegisterFile("weather_message.proto", fileDescriptor_798b5547218179bb) }

var fileDescriptor_798b5547218179bb = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4f, 0x4d, 0x2c,
	0xc9, 0x48, 0x2d, 0x8a, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x95, 0x12, 0x2a, 0xc9, 0x2f, 0xc8,
	0x4c, 0x8e, 0xcf, 0x2f, 0x28, 0xc9, 0xcc, 0xcf, 0x83, 0x48, 0x2a, 0xed, 0x64, 0xe4, 0x62, 0x0f,
	0x87, 0x68, 0x13, 0x12, 0xe2, 0x62, 0x49, 0xce, 0x2c, 0xa9, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x85, 0x14, 0xb8, 0xb8, 0x4b, 0x52, 0x73, 0x0b, 0x52, 0x8b, 0x12, 0x4b, 0x4a,
	0x8b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x98, 0x82, 0x90, 0x85, 0x40, 0xba, 0xca, 0x33, 0xf3,
	0x52, 0x24, 0x98, 0xc1, 0x52, 0x60, 0xb6, 0x90, 0x1c, 0x17, 0x57, 0x59, 0x66, 0x71, 0x66, 0x52,
	0x66, 0x0e, 0xc8, 0x3c, 0x16, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x24, 0x11, 0x21, 0x09, 0x2e, 0x76,
	0xa8, 0x5b, 0x25, 0x58, 0xc1, 0x96, 0xc1, 0xb8, 0x20, 0xd3, 0x4a, 0x32, 0x73, 0x53, 0x25, 0xd8,
	0x20, 0x6e, 0x00, 0xb1, 0xad, 0xc4, 0xba, 0xb6, 0x4a, 0xc0, 0x14, 0x4c, 0x42, 0x30, 0x9d, 0xd8,
	0xa2, 0x58, 0x72, 0x13, 0x33, 0xf3, 0x92, 0xd8, 0xc0, 0x5e, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0x7d, 0x35, 0xc8, 0x00, 0x01, 0x00, 0x00,
}
