name: Go

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true

    - name: Set up gox&ghr
      run: |
        go get github.com/mitchellh/gox
        go get github.com/tcnksm/ghr

    - name: Build
      run: |
        go run github.com/mitchellh/gox -verbose -osarch="linux/amd64 windows/amd64 darwin/amd64 darwin/arm64" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags="-X 'main.Version=${{ github.ref_name }}'" ./cmd/schema/
        go run github.com/tcnksm/ghr -u youla-dev -t $GHR_TOKEN -prerelease ${{ github.ref_name }}  dist/
