name: Go

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true

    - name: Set up gox&ghr
      run: |
        go get github.com/mitchellh/gox
        go get github.com/tcnksm/ghr

    - name: Build
      run: gox -arch="amd64" -os="darwin windows linux" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags="-X 'main.Version=0.5'" ./cmd/schema/*.go
